name: CD - Build & Deploy Portfolio

on:
  push:
    branches:
      - main # שים לב שזה תואם לשם ה-Branch שלך (main או master)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # הגדרת QEMU כדי שנוכל לבנות למעבדי ARM
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # בנייה ודחיפה של האימג' (רק הלקוח)
      - name: Build & Push Client Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # חשוב מאוד לשרת של אורקל!
          platforms: linux/arm64
          provenance: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-cd-demo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # העתקת קובץ ה-docker-compose לשרת
      - name: Copy docker-compose to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: 'docker-compose.yml'
          target: '~/app-for-CD' # התיקייה בשרת

      # התחברות לשרת וריענון הקונטיינר
      - name: Deploy on Oracle VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app-for-CD

            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/devops-cd-demo:latest

            echo "Restarting container..."
            docker compose down
            docker compose up -d --force-recreate

            echo "Deployment finished!"
